"""empty message

Revision ID: 1f9f0bb4758a
Revises: a5cffa318ac2
Create Date: 2023-12-15 18:47:57.189826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f9f0bb4758a'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=550), nullable=False),
    sa.Column('height', sa.String(length=25), nullable=False),
    sa.Column('mass', sa.String(length=25), nullable=False),
    sa.Column('hair_color', sa.String(length=25), nullable=False),
    sa.Column('skin_color', sa.String(length=25), nullable=False),
    sa.Column('eye_color', sa.String(length=25), nullable=False),
    sa.Column('birth_year', sa.String(length=25), nullable=False),
    sa.Column('gender', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('planets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('diameter', sa.String(length=25), nullable=False),
    sa.Column('rotation_period', sa.String(length=25), nullable=False),
    sa.Column('orbital_period', sa.String(length=25), nullable=False),
    sa.Column('gravity', sa.String(length=55), nullable=False),
    sa.Column('population', sa.String(length=25), nullable=False),
    sa.Column('climate', sa.String(length=25), nullable=False),
    sa.Column('terrain', sa.String(length=25), nullable=False),
    sa.Column('surface_water', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('favorite__people',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('people_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite__planets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('planets_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['planets_id'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('username')

    op.drop_table('favorite__planets')
    op.drop_table('favorite__people')
    op.drop_table('planets')
    op.drop_table('people')
    # ### end Alembic commands ###
